Emit the 2026-09-02 Arches stitched waveforms as a C header.
//
// GENERATED by tools/arches_fixtures.py -- do not edit.
// Source: /Users/davidbrown/ngr-telemetry/pi/NGR/telemetry/all_20260902.log
//
// Every passage Toby reported as STITCHED on 2026-09-02, with the
// waveform he published for it. Two classes, and they are not the same
// fault:
//
//   SLIP    paused 1.6 to 4.1 s. He rested CLEAR of the magnet,
//           departed, entered the field, and the wheels spun inside the
//           arc before they caught. The record has a JOIN in it -- a
//           level change no locomotive can make.
//   DWELL   paused 35 to 37 s. He came to rest INSIDE the field and sat
//           there for the station dwell. One of these stitched and was
//           refused; the other never recorded a departure at all.
//
// `splice` is the first sample of the departure segment, or -1 when the
// record has no departure in it.
#pragma once
#include <stdint.h>

struct ArchesFixture {
  const char* tag; const char* what;
  uint8_t  polarity; uint16_t decimation; uint16_t gain; uint16_t peak;
  float    publishedResidual;
  uint32_t openedAtMs, closedAtMs;
  int      splice;          // first sample of the departure segment, -1 = none
  bool     accepted;        // what the CURRENT one-Gaussian recognizer ruled
  const int16_t* v;
};

// A1967_CW  mm 109 -> 110, peak 138 of gain 218, paused 1600 ms, residual 0.1967 -- REFUSED
// CW Arches -- slip, wheels spun then caught
static const int16_t FX_A1967_CW[] = {
  31,34,33,30,32,34,38,37,37,36,34,32,34,38,38,39,
  40,37,40,38,40,40,42,43,45,43,43,38,40,39,40,41,
  42,41,40,45,46,44,45,43,47,51,54,54,54,55,54,56,
  53,-5,58,57,59,56,58,58,59,59,59,59,61,60,60,61,
  61,62,64,63,62,62,62,65,65,66,69,70,69,69,64,64,
  66,68,71,65,68,74,76,76,73,81,75,75,76,78,77,77,
  80,78,79,78,82,82,82,82,138,139,136,138,137,136,134,133,
  131,133,133,132,129,126,125,124,125,123,123,123,122,113,113,109,
  122,114,112,112,110,106,106,105,102,102,98,98,94,92,91,86,
  80,78,81,79,75,74,74,69,72,65,66,62,59,59,58,58,
  50,53,49,46,44,42,41,40,40,31,34,30,26,27,24,22,
  18,18,18,
};
static const ArchesFixture AX_A1967_CW = { "A1967_CW", "CW Arches -- slip, wheels spun then caught", 1, 2, 218, 138, 0.1967f, 361069u, 363366u, 104, false, FX_A1967_CW };

// A1223_CW  mm 110 -> 111, CW, peak 143, residual 0.1223, paused 4126 ms -- ACCEPTED
// NO WAVEFORM. The build publishes one only when the recognizer
// REFUSES, so the stitched arc that PASSED was never transmitted.
// Recovering it is the reason to dump every stitched passage.

// A1818_CW  mm 109 -> 110, peak 140 of gain 218, paused 4075 ms, residual 0.1818 -- REFUSED
// CW Arches -- slip, wheels spun then caught
static const int16_t FX_A1818_CW[] = {
  23,25,24,24,24,26,57,26,24,25,25,24,24,24,19,25,
  26,26,26,25,26,26,27,27,27,27,28,26,31,27,27,27,
  26,28,28,31,29,29,29,30,30,26,26,26,32,33,31,32,
  33,35,35,35,33,36,28,36,37,37,37,40,38,42,39,37,
  38,37,39,39,40,39,40,39,41,39,43,43,43,41,41,44,
  43,43,39,46,45,43,44,47,45,45,47,45,41,40,41,48,
  47,56,49,49,48,49,53,51,51,53,55,55,56,57,55,56,
  57,58,58,58,58,56,58,58,59,58,59,58,59,59,60,59,
  60,60,61,61,62,65,64,65,64,67,67,65,68,69,71,69,
  64,65,65,69,65,67,75,76,74,74,74,76,77,76,76,75,
  78,78,77,80,79,80,140,140,123,133,133,139,138,138,138,137,
  136,135,135,134,133,133,131,131,128,116,122,122,127,120,122,120,
  121,123,119,117,119,119,117,116,115,112,113,109,111,108,110,105,
  108,108,106,104,104,103,105,101,100,97,107,103,94,95,100,97,
  96,96,95,92,91,90,91,90,90,88,88,87,84,86,81,81,
  83,77,79,77,76,73,74,73,72,71,69,69,69,65,64,61,
  61,58,58,57,57,56,55,53,52,54,49,51,46,44,43,36,
  37,36,31,32,31,35,30,32,29,27,26,26,25,26,25,23,
  21,19,21,
};
static const ArchesFixture AX_A1818_CW = { "A1818_CW", "CW Arches -- slip, wheels spun then caught", 1, 2, 218, 140, 0.1818f, 1452424u, 1457446u, 166, false, FX_A1818_CW };

// A1810_CW  mm 111 -> 112, peak 176 of gain 213, paused 35002 ms, residual 0.1810 -- REFUSED
// CW Arches -- station dwell INSIDE the field
static const int16_t FX_A1810_CW[] = {
  32,33,35,40,35,37,37,39,41,37,40,40,42,41,43,41,
  43,42,45,44,44,40,41,46,49,42,43,47,46,45,48,51,
  50,50,52,54,54,56,57,54,56,63,64,64,65,65,59,58,
  62,65,73,73,73,73,73,72,73,75,75,75,75,77,76,76,
  77,78,79,78,82,85,84,86,79,86,88,89,90,90,90,90,
  90,91,93,92,94,94,94,96,102,96,97,100,100,101,102,103,
  101,106,100,102,100,107,102,104,106,106,107,109,107,107,107,107,
  107,108,117,116,117,117,117,113,117,115,114,108,113,110,113,121,
  122,122,122,121,120,122,122,122,123,125,122,124,126,124,126,126,
  126,126,128,129,128,122,129,129,129,129,130,129,130,134,130,132,
  133,132,133,133,132,134,136,136,134,133,138,137,136,138,128,128,
  138,138,136,139,139,139,139,139,139,139,140,139,177,176,174,172,
  171,169,168,168,157,165,160,156,154,155,153,150,146,144,143,139,
  137,134,133,130,126,123,122,120,118,113,112,109,107,98,94,92,
  96,93,92,89,86,81,77,75,73,72,66,64,59,58,54,52,
  66,43,43,41,38,36,34,26,22,22,26,24,24,19,
};
static const ArchesFixture AX_A1810_CW = { "A1810_CW", "CW Arches -- station dwell INSIDE the field", 1, 4, 213, 176, 0.1810f, 241180u, 277812u, 188, false, FX_A1810_CW };

// A2695_CCW  mm 107 -> 106, peak 134 of gain 204, paused 37211 ms, residual 0.2695 -- REFUSED
// CCW Arches -- station dwell INSIDE the field; ARRIVAL ONLY, no departure recorded
static const int16_t FX_A2695_CCW[] = {
  29,29,32,29,29,29,41,40,56,36,35,36,30,29,31,32,
  32,34,35,34,37,36,35,35,38,38,39,38,38,39,54,40,
  40,42,43,42,41,46,45,44,45,43,43,45,44,45,46,45,
  47,47,47,47,47,46,49,50,56,57,58,55,50,49,53,55,
  54,56,55,53,56,59,56,59,56,59,59,59,59,60,61,61,
  61,61,61,61,61,61,63,62,64,63,64,65,63,65,63,66,
  66,72,65,70,70,70,70,67,72,71,73,74,82,79,77,74,
  77,79,79,79,74,77,77,76,78,78,77,80,80,82,78,83,
  84,80,83,83,86,86,86,92,93,92,93,96,92,93,93,93,
  94,93,94,93,98,94,97,93,105,97,96,99,96,99,99,99,
  102,97,102,102,103,103,106,105,106,107,105,108,107,109,106,107,
  109,110,110,110,110,109,112,111,111,114,115,112,115,118,116,110,
  110,110,114,114,114,115,116,115,118,118,120,116,120,118,121,122,
  122,120,123,127,126,125,125,126,126,130,130,126,127,131,128,125,
  130,143,126,125,126,128,127,125,128,130,131,131,130,132,134,134,
  132,132,
};
static const ArchesFixture AX_A2695_CCW = { "A2695_CCW", "CCW Arches -- station dwell INSIDE the field; ARRIVAL ONLY, no departure recorded", 0, 2, 204, 134, 0.2695f, 323985u, 362044u, -1, false, FX_A2695_CCW };

static const ArchesFixture* const ARCHES_FIXTURES[] = { &AX_A1967_CW, &AX_A1818_CW, &AX_A1810_CW, &AX_A2695_CCW };
static const int ARCHES_FIXTURE_COUNT = 4;
