#!/bin/sh
# Regenerate 0070.diff: everything the field-test build changes in firmware/,
# against the last accepted firmware commit. Run after editing anything under
# firmware/test-programs/NAVI_ONE/.
set -eu
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/../.." && pwd)
rel="firmware/test-programs/NAVI_ONE"
base=${NAVI_ONE_BASE:-1b8b828}
cd "$repo"
{
  echo "# THE EXACT DIFF of the decision 0070 field-test build, against $base"
  echo "# (NAVI_ONE 0.9, the last accepted firmware commit). Generated by:"
  echo "#   sh tools/interrupted_replay/make_diff.sh"
  echo "#"
  echo "# APPLIED. This is what is in firmware/ now. It is an EXPERIMENTAL"
  echo "# FIELD-TEST BUILD and is not field-accepted NAVI_ONE 1.0."
  echo "#"
  echo "# MagnetRecognizer.h and WaveformWindow.h do not appear below: this"
  echo "# design does not touch them, and no threshold was moved."
  echo "#"
  git diff "$base" -- "$rel"
  for f in tests/gate_interrupted.cpp tests/fixtures_captures.h; do
    if ! git ls-files --error-unmatch "$rel/$f" >/dev/null 2>&1; then
      echo "# NEW FILE, not yet tracked: $rel/$f"
    fi
  done
} > "$here/0070.diff"
echo "wrote $here/0070.diff"
wc -l < "$here/0070.diff"
