#!/bin/sh
# Regenerate 0070.diff from the proposed tree. Run after editing anything under
# tools/interrupted_replay/proposed/.
set -eu
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/../.." && pwd)
src="firmware/test-programs/NAVI_ONE"
cd "$repo"
{
  echo "# THE EXACT DIFF decision 0070 proposes. Generated by:"
  echo "#   sh tools/interrupted_replay/make_diff.sh"
  echo "# NOT APPLIED. firmware/ is untouched until the operator ratifies."
  echo "#"
  for f in HallCapture.h Navigator.h LocoConfig.h NAVI_ONE.ino; do
    diff -u "$src/$f" "$here/proposed/$f" \
      | sed -e "1s|.*|--- $src/$f|" -e "2s|.*|+++ $src/$f (proposed)|" || true
  done
  diff -u "$src/tests/run_tests.sh" "$here/proposed/tests/run_tests.sh" \
    | sed -e "1s|.*|--- $src/tests/run_tests.sh|" -e "2s|.*|+++ $src/tests/run_tests.sh (proposed)|" || true
  echo "# NEW FILES (added, no diff):"
  echo "#   $src/tests/gate_interrupted.cpp"
  echo "#   $src/tests/fixtures_captures.h"
} > "$here/0070.diff"
echo "wrote $here/0070.diff"
