#!/usr/bin/env python3
"""Turn the field waveform CSVs into a C++ test fixture header.

The captures themselves stay OUTSIDE the working tree, by the rule in
tools/fetch_pi_telemetry.sh that git must not be able to rewrite them. What is
committed is this generator and its output: a header of the exact samples the
firmware recorded, so gate 12 is hermetic and anyone can re-derive it.

    python3 tools/interrupted_replay/make_fixtures.py ~/ngr-telemetry/waveforms
"""
import os, sys

WANT = [
  ("F09A", "finding 09 A -- latched DC offset, Toby stationary throughout",
   "20260901_mm41/waveform_20260901T162648_668_slot3.csv"),
  ("F09B", "finding 09 B -- the same offset, held 9m15s across two declarations",
   "20260901_mm41/waveform_20260901T162648_668_slot4.csv"),
  ("F11",  "finding 11 -- Grillers CCW, parked ON MM59, 37.7 s passage",
   "20260901_ccw_mm60/waveform_20260901T182114_489_slot1.csv"),
  ("F13",  "finding 13 -- Arches CCW, parked in MM106's fringe, magnet on departure",
   "20260901_arches2/waveform_20260901T191738_707_slot3.csv"),
]

def load(path):
    h, v = {}, []
    for line in open(path):
        line = line.strip()
        if line.startswith('#'):
            k, x = line[1:].split(',', 1); h[k] = x
        elif line and not line.startswith('sample'):
            v.append(int(line.split(',')[1]))
    return h, v

def main():
    base = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/ngr-telemetry/waveforms")
    out = ["// GENERATED by tools/interrupted_replay/make_fixtures.py -- do not edit.",
           "//",
           "// The four field records decision 0070 is argued from, verbatim: the",
           "// oriented, entry-baseline-relative samples the firmware itself recorded and",
           "// published on diag/waveform. Nothing here is reconstructed or smoothed.",
           "//",
           "// A record is DECIMATED: each stored sample is one real 1 kHz reading, and",
           "// `decimation` says how many milliseconds separate it from the next. The",
           "// readings in between were never transmitted and cannot be recovered -- see",
           "// gate 12 section D for what the harness does about that, and decision 0070",
           "// for what it therefore does not prove.",
           "#pragma once", "#include <stdint.h>", "",
           "struct CaptureFixture {",
           "  const char* tag; const char* what;",
           "  uint8_t  polarity; uint16_t decimation; uint16_t gain;",
           "  uint32_t openedAtMs, closedAtMs;",
           "  uint16_t n; const int16_t* v;",
           "};", ""]
    entries = []
    for tag, what, rel in WANT:
        h, v = load(os.path.join(base, rel))
        gain = int(h.get("gain") or round(int(h["peakCounts"]) / float(h["amplitudeRatio"])))
        out.append("// %s\n// %s" % (what, rel))
        out.append("static const int16_t FX_%s[] = {" % tag)
        for i in range(0, len(v), 16):
            out.append("  " + ",".join("%d" % x for x in v[i:i+16]) + ",")
        out.append("};")
        entries.append('  { "%s", "%s", %s, %s, %d, %sUL, %sUL, %d, FX_%s },'
                       % (tag, what, h["polarity"], h["decimation"], gain,
                          h["openedAtMs"], h["closedAtMs"], len(v), tag))
        out.append("")
    out.append("static const CaptureFixture CAPTURES[] = {")
    out += entries
    out.append("};")
    out.append("static const int CAPTURE_COUNT = (int)(sizeof(CAPTURES)/sizeof(CAPTURES[0]));")
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "proposed", "tests", "fixtures_captures.h")
    open(dst, "w").write("\n".join(out) + "\n")
    print("wrote %s (%d records)" % (dst, len(entries)))

main()
