#!/usr/bin/env python3
"""Emit the 2026-09-02 Arches stitched waveforms as a C header.

These are the records the two-sided model has to be judged on: the firmware's
own published samples, verbatim, not synthetic Gaussian halves. Run against a
fetched telemetry mirror:

    python3 tools/arches_fixtures.py <all_YYYYMMDD.log> \
        > firmware/test-programs/NAVI_ONE/tests/fixtures_arches.h

The accepted stitched passage of 11:03:54 (residual 0.1223) is NOT here and
cannot be: the build dumps a waveform only when the recognizer refuses one, so
the one stitched arc that passed was never transmitted. Its scalar record is
carried below instead, and recovering the waveform is the reason to dump every
stitched passage rather than only the refused ones.
"""
import base64, json, struct, sys, collections

HDR = "<8B6H2f3I"
assert struct.calcsize(HDR) == 40

def blocks(path):
    """Every complete published waveform, keyed by (slotTotal, slotIndex, line)."""
    out = collections.OrderedDict()
    with open(path, errors="replace") as f:
        for n, line in enumerate(f, 1):
            if "diag/waveform" not in line:
                continue
            try:
                j = json.loads(line.split("\t")[-1])
            except Exception:
                continue
            b = base64.b64decode(j["payload_b64"])
            h = struct.unpack(HDR, b[:40])
            si, st, ci, ct, pol, outc, ism, shp = h[0:8]
            scount, ccount, coff, dec, peak, gain = h[8:14]
            ratio, resid = h[14:16]
            gap, opened, closed = h[16:19]
            key = (st, si, n if ci == 0 else None)
            # chunks of one slot arrive consecutively; fold them onto the first
            k = next((k for k in reversed(out) if k[0] == st and k[1] == si
                      and out[k]["open"]), None)
            if k is None:
                k = (st, si, n)
                out[k] = dict(line=n, pol=pol, outc=outc, dec=dec, peak=peak,
                              gain=gain, resid=resid, gap=gap, opened=opened,
                              closed=closed, n=scount, s={}, open=True)
            d = out[k]
            for i, v in enumerate(struct.unpack("<%dh" % ccount, b[40:40+ccount*2])):
                d["s"][coff + i] = v
            if len(d["s"]) >= d["n"]:
                d["open"] = False
    return out

def emit(name, what, d, splice):
    s = [d["s"][i] for i in sorted(d["s"])]
    print("\n// %s" % what)
    print("//   published %s, residual %.4f, peak %d of gain %d, decimation %d ms" %
          (name, d["resid"], d["peak"], d["gain"], d["dec"]))
    print("static const int16_t FX_%s[] = {" % name)
    for k in range(0, len(s), 16):
        print("  " + ",".join("%d" % v for v in s[k:k+16]) + ",")
    print("};")
    print("static const ArchesFixture AX_%s = { \"%s\", \"%s\", %d, %d, %d, %d, "
          "%.4ff, %uu, %uu, %d, FX_%s };" %
          (name, name, what, d["pol"], d["dec"], d["gain"], d["peak"],
           d["resid"], d["opened"], d["closed"], splice, name))
    return len(s)

def stitched_events(path):
    """Every passage the firmware itself reported as stitched, from the nav
    events -- not guessed from the waveform's size or its residual."""
    seen, out = set(), []
    for line in open(path, errors="replace"):
        if "/mm/marker" not in line:
            continue
        try:
            j = json.loads(line.split("\t")[-1])
        except Exception:
            continue
        # Every passage that spanned or abutted a stop: the ones the firmware
        # labelled stitched, and the ones it did NOT -- a passage that opened
        # on a stationary artifact and ran through the whole dwell is not
        # labelled anything, and it is the worst of them.
        if not j.get("stitched") and not (j.get("shape") and j.get("resid", 0) > 0.13):
            continue
        k = (j.get("resid"), j.get("paused_ms"), j.get("mm"))
        if k in seen:
            continue
        seen.add(k)
        j["_t"] = line.split("\t")[0]
        out.append(j)
    out.sort(key=lambda j: j["_t"])
    return out

def main():
    log = sys.argv[1]
    bs = blocks(log)
    evs = stitched_events(log)
    print(__doc__.split("\n\n")[0])
    print("//")
    print("// GENERATED by tools/arches_fixtures.py -- do not edit.")
    print("// Source: %s" % log)
    print("//")
    print("// Every passage Toby reported as STITCHED on 2026-09-02, with the")
    print("// waveform he published for it. Two classes, and they are not the same")
    print("// fault:")
    print("//")
    print("//   SLIP    paused 1.6 to 4.1 s. He rested CLEAR of the magnet,")
    print("//           departed, entered the field, and the wheels spun inside the")
    print("//           arc before they caught. The record has a JOIN in it -- a")
    print("//           level change no locomotive can make.")
    print("//   DWELL   paused 35 to 37 s. He came to rest INSIDE the field and sat")
    print("//           there for the station dwell. One of these stitched and was")
    print("//           refused; the other never recorded a departure at all.")
    print("//")
    print("// `splice` is the first sample of the departure segment, or -1 when the")
    print("// record has no departure in it.")
    print("#pragma once")
    print("#include <stdint.h>")
    print("""
struct ArchesFixture {
  const char* tag; const char* what;
  uint8_t  polarity; uint16_t decimation; uint16_t gain; uint16_t peak;
  float    publishedResidual;
  uint32_t openedAtMs, closedAtMs;
  int      splice;          // first sample of the departure segment, -1 = none
  bool     accepted;        // what the CURRENT one-Gaussian recognizer ruled
  const int16_t* v;
};""")
    out = []
    for ev in evs:
        # match the published waveform to its event by peak and residual: the
        # header carries both, and no two passages today share them.
        b = next((d for d in bs.values()
                  if d["peak"] == ev["peak"] and abs(d["resid"] - ev["resid"]) < 1e-4), None)
        tag = "A%04d_%s" % (int(round(ev["resid"] * 10000)), ev["dir"])
        if b is None:
            print("\n// %s  mm %d -> %d, %s, peak %d, residual %.4f, paused %d ms -- %s"
                  % (tag, ev["mm"], ev["tgt"], ev["dir"], ev["peak"], ev["resid"],
                     ev["paused_ms"], "ACCEPTED"))
            print("// NO WAVEFORM. The build publishes one only when the recognizer")
            print("// REFUSES, so the stitched arc that PASSED was never transmitted.")
            print("// Recovering it is the reason to dump every stitched passage.")
            continue
        s = [b["s"][i] for i in sorted(b["s"])]
        m = list(s)
        for i in range(1, len(s) - 1):
            m[i] = sorted(s[i-1:i+2])[1]
        splice = max(range(1, len(m)), key=lambda i: abs(m[i] - m[i-1]))
        if abs(m[splice] - m[splice-1]) < 30:
            splice = -1
        wall = b["closed"] - b["opened"]
        if not ev.get("stitched"):
            kind = ("opened on a stationary artifact and spanned the whole dwell"
                    if wall > 10000 else "refused on shape, no stop in it")
        elif ev["paused_ms"] < 10000:
            kind = "slip, wheels spun then caught"
        else:
            kind = "station dwell INSIDE the field"
        # Name the platform from the marker, not from the file's title: the
        # dwell faults are not confined to Arches and calling them all Arches
        # would hide that.
        STATIONS = {15: "Patio", 63: "Grillers", 108: "Arches", 157: "Bamboo"}
        near = min(STATIONS, key=lambda c: min((ev["mm"] - c) % 171, (c - ev["mm"]) % 171))
        off = min((ev["mm"] - near) % 171, (near - ev["mm"]) % 171)
        where = "%s%s" % (STATIONS[near], "" if off <= 3 else " (%d markers out)" % off)
        # "ARRIVAL ONLY" means the firmware said it stitched and the record has
        # no join in it. A passage that never stitched has no departure segment
        # to be missing.
        missing = "; ARRIVAL ONLY, no departure recorded" if (ev.get("stitched") and splice < 0) else ""
        what = "%s %s -- %s%s" % (ev["dir"], where, kind, missing)
        print("\n// %s  mm %d -> %d, peak %d of gain %d, paused %d ms, residual %.4f -- %s"
              % (tag, ev["mm"], ev["tgt"], ev["peak"], ev["gain"], ev["paused_ms"],
                 ev["resid"], "ACCEPTED" if ev["event"] == "AGREE" else "REFUSED"))
        print("// %s" % what)
        print("// wall %u ms, %u samples at %u ms each = %u ms of record"
              % (wall, len(s), b["dec"], len(s) * b["dec"]))
        print("static const int16_t FX_%s[] = {" % tag)
        for k in range(0, len(s), 16):
            print("  " + ",".join("%d" % v for v in s[k:k+16]) + ",")
        print("};")
        print("static const ArchesFixture AX_%s = { \"%s\", \"%s\", %d, %d, %d, %d, "
              "%.4ff, %uu, %uu, %d, %s, FX_%s };"
              % (tag, tag, what, b["pol"], b["dec"], b["gain"], b["peak"], b["resid"],
                 b["opened"], b["closed"], splice,
                 "true" if ev["event"] == "AGREE" else "false", tag))
        out.append(tag)
    print("\nstatic const ArchesFixture* const ARCHES_FIXTURES[] = { %s };"
          % ", ".join("&AX_" + t for t in out))
    print("static const int ARCHES_FIXTURE_COUNT = %d;" % len(out))

main()
